### ISSUE TITLE
Code generation broken on https://atacama.informatik.uni-bremen.de/

### ISSUE THREAD

**Issue by Teufelchen1** [ATACAMA-Project/cddl_web_tools#2]
Hi 👋 

just want leave the note that using the "Code Generation" tab on https://atacama.informatik.uni-bremen.de/ is currently broken.
E.g. if you input:
```CDDL
object = {
name: text
subs: [* sub]
}

sub = {
id: uint
alias: text
}
```

and hit `Submit` you will receive:
```
Internal error:

No space left on device (os error 28) at path "/tmp/.tmp6YB6Mb"
```

**Comment by SimonIT** [comment]
Hi, thanks for reporting the problem. We were already aware of it. I made some space on the server so the generation should work again
